version: '3.7'

services:
  ssweb:
    image: vss365today-web:latest
    container_name: vss365today-web
    restart: unless-stopped
    volumes:
      - ../web:/app
      - ../web/log:/var/log
      - ../secrets:/app/secrets
      - ../static/images:/app/src/static/prompt-images
      - ../static/downloads:/app/src/static/downloads
    ports:
      - 127.0.0.1:5002:80
    environment:
      - FLASK_ENV=production
      - SYS_VARS_PATH=/app/secrets
    entrypoint:
      - sh
      - ./run-app.sh
    networks:
      - vss365today

  api:
    image: vss365today-api:latest
    container_name: vss365today-api
    restart: unless-stopped
    volumes:
      - ../api:/app
      - ../api/log:/var/log
      - ../secrets:/app/secrets
      - ../static/images:/app/images
      - ../static/downloads:/app/downloads
    ports:
      - 127.0.0.1:5003:80
    environment:
      - FLASK_ENV=production
      - SYS_VARS_PATH=/app/secrets
    entrypoint:
      - sh
      - ./run-app.sh
    networks:
      - vss365today

  finder:
    image: vss365today-finder:latest
    container_name: vss365today-finder
    restart: unless-stopped
    volumes:
      - ../finder:/app
      - ../secrets:/app/secrets
      - ../static/downloads:/app/downloads
    environment:
      - FLASK_ENV=production
      - SYS_VARS_PATH=/app/secrets
      - DOWNLOADS_PATH=/app/downloads
      - SCHEDULE_TIMES=["05 4", "25 4", "45 4", "05 5"]
    entrypoint:
      - python
      - ./finder.py
      - --schedule
    networks:
      - vss365today

  db:
    image: mariadb:10.4
    container_name: database
    restart: unless-stopped
    volumes:
      - ../api/db:/docker-entrypoint-initdb.d
      - ../db/:/var/lib/mysql
      - ../secrets:/secrets
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_DATABASE=vss365today
      - MYSQL_USER_FILE=/secrets/DB_USERNAME
      - MYSQL_PASSWORD_FILE=/secrets/DB_PASSWORD
      - MYSQL_ROOT_PASSWORD_FILE=/secrets/DB_PASSWORD_ROOT
    networks:
      - vss365today

  # Run a database backup at midnight every Sunday
  mysql-backup:
    image: databack/mysql-backup
    container_name: mysql-backup
    restart: unless-stopped
    volumes:
      - ../backup:/backup
    environment:
      - DB_DUMP_SAFECHARS=true
      - DB_DUMP_CRON=0 0 * * 0
      - DB_SERVER=vss365today-db
      - DB_PORT=3306
      - DB_NAMES=vss365today
      - DB_DUMP_TARGET=/backup
      - NICE=true
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    networks:
        - vss365today

networks:
  vss365today:
    driver: bridge
